version: "3.3"
services:
  builder:
    build:
      context: ./builder
      cache_from:
        - ${COMPOSE_PROJECT_NAME}-builder:latest
    image: ${COMPOSE_PROJECT_NAME}-builder:latest
    volumes:
      - type: bind
        source: ..
        target: /project
    depends_on:
      - test-consul
    links:
      - test-consul
    environment:
      - TEST_CONSUL_SCHEME=http
      - TEST_CONSUL_ADDRESS=test-consul:8500
  test-consul:
    image: consul:latest
    environment:
      - CONSUL_BIND_INTERFACE=eth0
